### ISSUE TITLE
[BUG] Found ER_Tags as Tags in Swate

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate-templates#106]
This image lead me to open this issue:

![image](https://github.com/nfdi4plants/Swate-templates/assets/39732517/5a1ef555-1e53-4fe0-ae3c-2ffff3d6b8e3)

In my opinion we should avoid recycling `ER_Tags` as `Tag`s to reduce visual clutter and don't make the user question why they can click on ER_Tag or Tag PRIDE.

Below you can find a summary of templates with this issue:

## Found ER_Tags as tag `PRIDE` in:
- **RPTU - MBS, growth** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus*)
- **RPTU - MBS, growth TurboID** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus, David  Zimmer*)
- **RPTU - MBS, cell disruption** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus*)
- **RPTU - MBS, data processing** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus*)
- **RPTU - MBS, mass spectrometry** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus*)
- **RPTU - MBS, protein extraction** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus*)
- **RPTU - MBS, sample preparation** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus*)
- **RPTU - MBS, protein standard preparation** by (*Frederik  Sommer, Martin  Kuhl, Oliver  Maus*)
- **Protein extraction** by (*Oliver  Maus, Dominik  Brilhaus*)
- **Proteomics MassSpec Assay** by (*Oliver  Maus*)
- **Proteomics Computational Analyses** by (*Oliver  Maus*)
- **Data Processing (PRIDE minimal)** by (*Oliver  Maus*)
- **Measurement (PRIDE minimal)** by (*Oliver  Maus*)
- **Sample Preparation (PRIDE minimal)** by (*Oliver  Maus*)
## Found ER_Tags as tag `GEO` in:
- **RNA extraction** by (*Hajira  Jabeen, Dominik  Brilhaus*)
- **RNASeq Assay** by (*Hajira  Jabeen, Dominik  Brilhaus*)
- **RNASeq Computational Analysis** by (*Hajira  Jabeen, Dominik  Brilhaus, Oliver  Maus, Martin  Kuhl*)
- **GEO - Minimal information RNA assays** by (*Martin  Kuhl*)
- **GEO - Minimal information computational analysis** by (*Martin  Kuhl*)
- **GEO - Minimal information RNA extraction** by (*Martin  Kuhl*)
- **GEO - Minimal information plant growth** by (*Martin  Kuhl*)

# Code 

```fsharp
// .fsx file

#r "nuget: ARCtrl, 1.0.7"

let templates = 
  ARCtrl.Template.Web.getTemplates None |> Async.RunSynchronously

let ER_Tags = ARCtrl.Template.Templates.getDistinctEndpointRepositories (templates)
let Tags = ARCtrl.Template.Templates.getDistinctTags (templates)
ER_Tags.Length // 10
Tags.Length //102

// These are ER_Tags also used as Tags
let ER_TagsAsTags = Tags |> Array.filter (fun tag -> ER_Tags |> Array.contains tag)


for (tag) in ER_TagsAsTags do
  let temps = ARCtrl.Template.Templates.filterByOntologyAnnotation ([|tag|]) templates
  printfn "## Found ER_Tags as tag `%s` in:" tag.NameText
  for template in temps do 
    let authors = 
      template.Authors 
      |> Array.map (fun a -> 
        let names = [|a.FirstName; a.MidInitials; a.LastName|] |> Array.map (fun n -> Option.defaultValue "" n)
        sprintf "%s %s %s" names.[0] names.[1] names.[2]
      ) 
      |> String.concat ", "
    printfn "- **%s** by (*%s*)" (template.Name.Trim()) (authors.Trim())
```

**Comment by StellaEggels** [comment]
For me the question is also if ER tags should be added for templates that don't directly correspond to repositories. Again maybe something to be discussed.
