### ISSUE TITLE
[FEATURE] Templates for ENA checklists

### ISSUE THREAD

**Issue by StellaEggels** [nfdi4plants/Swate-templates#113]
Templates for the ENA checklists relevant for plant sciences and microbiology should be added.

- [ ] Templates for plant-related ENA checklists
- [ ] Templates for microbiology-related ENA checklists

The checklists can be found here:
https://www.ebi.ac.uk/ena/browser/checklists

**Comment by xiaoranzhou** [comment]
Now we can generate new ENA templates by using the [ENA checklist to Swate template tool.](https://xrzhou.com/ena2swate/)
We just need to decide which templates can be put into the git repo 😄
