### ISSUE TITLE
Use of the category names (e.g. Characteristic, Parameter, etc.) in curated data analysis templates

### ISSUE THREAD

**Issue by UrsulaE** [nfdi4plants/Swate-templates#169]
Thanks for providing curated templates for data analysis! For a project, I am trying to create a general template for computational analyses. Re templates

RNASeq computational analysis v. 1.2.0
Proteomics computational analysis v. 1.1.6
Metabolomics computational analysis v. 1.1.8
MIMAG - Metagenomics computational analysis v 1.0.1

What is the rationale behind using "Parameter" for all/almost all column headers? E.g. I would have assumed that a Project name is a "Characteristic" or a software a "Component". Sorry if I missed this discussion in another place.

**Comment by Brilator** [comment]
Quick guess without looking into details: the templates (building blocks in there) could require some updates. Some of them are from very early stages. Type "Component" was not always available in Swate. 

"Project name" should presumably not exist anywhere in a template, but rather on investigation / study top-level metadata level.

**Comment by StellaEggels** [comment]
Also in many other templates some categories/building block types should be updated. I will start with correcting some of which I am sure they should be changed, but when you notice unfitting categories feel free to change them too.

**Comment by UrsulaE** [comment]
Thanks Stella, will do that. I was not sure whether I could just start fiddling with Swate Templates that others have uploaded, especially if there appears to be a pattern. Would it be good style to contact the original author first or can I just upload new versions?
