### ISSUE TITLE
[BUG] Update tags (in basically all templates)

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate-templates#22]
**Describe the bug**
The template "RNA extraction" (file: 2EXT01_RNA) contains both `#ER list` *GEO* and `#TAGS list` *er:GEO*.

The latter can be removed:
![image](https://user-images.githubusercontent.com/39732517/191443169-9a70e9d0-4008-47c1-8abb-7a9000245b5a.png)

**Comment by Brilator** [comment]
**Add** tags for 

- [ ] ER
- [ ] Minimal Standard (MIBBI, MIAPPE, MIGS, etc.)

**Remove** tags for "Protocol Type"
-> handle via template column #24

**Comment by Martin-Kuhl** [comment]
- [ ] RNASeq: Dominik
- [ ] Genomics: Xiaoran
- [ ] Proteomics: Oliver
- [ ] Metabolomics: Martin
- [ ] Imaging: Andrea/Martin

**Comment by Freymaurer** [comment]
What is the current state of this issue?

**Comment by StellaEggels** [comment]
Tags of curated templates are now generally ontology-supported. ER and minimum information standard templates all contain the respective tags of the ER/standard once. Protocol type tags will not be added at this point.
