### ISSUE TITLE
[FEATURE] Restructure Swate templates repository

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/Swate-templates#30]
As discussed yesterday, we need to revise and update the Swate templates repository. This includes:
- updating the README.md
  - contribution guidelines
  - intended use of templates together with future converters.
- deepening the folder structure
- evaluation of .xlsx diff usage to track changes in the templates

**Comment by Freymaurer** [comment]
I added a bit more depth to the folder structure and will observe the next few .xlsx revisions and adapt both readmes and folderstructure accordingly.
