### ISSUE TITLE
[FEATURE] Discuss usage of ontologies for tags in template metadata

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/Swate-templates#33]
Swate templates can already be tagged with information to improve the search function, e.g., who created the templated or for which repository they are intended. 
Currently, these tags are free-text. We need to further discuss the usage and the implementation of ontology terms for at least some of these tags.

**Comment by Brilator** [comment]
#22

**Comment by Freymaurer** [comment]
This is discussed in #22. closing here
