### ISSUE TITLE
[BUG] Check all templates for NFDI4PSO terms

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate-templates#49]
**Describe the bug**

Some templates include NFDI4PSO terms, which need to be replaced by DPBO terms.

**Comment by Martin-Kuhl** [comment]
- [ ] RNASeq: Dominik
- [ ] Genomics: Xiaoran
- [ ] Proteomics: Oliver
- [ ] Metabolomics: Martin
- [ ] Imaging: Andrea/Martin
