### ISSUE TITLE
[FEATURE] Template formats that encurage the correct usage of Characteristics and Parameters

### ISSUE THREAD

**Issue by WaljaWanney** [nfdi4plants/Swate-templates#63]
### Problem
In the ISA-tab study and assay files, there is a strict differentiation between Source, Sample, and Extract (etc), and Protocols. In contrast, in SWATE, each input is considered a source, and each output is treated as a sample. Consequently, a sample in one file can be or must be the source of another file.

Furthermore, in ISA-tab format, it is strictly defined that Sources, Samples, and Extracts (etc.) can only have Characteristics, while Protocols can have (Performer, Data), Parameters, Components, and Factors. As far as I understood the ISA-tab format, the order of the columns is also indicative of the relationship between them.

In many (curated) SWATE templates Characteristics are mixed with Parameters, Components and Factors. It feels like this disregards the significance of the of the column order, that makes it obvious in ISA-tab files e.g which Parameter is connected to which Protocol and which Characteristic is connected to which Source.

### Solution
One solution could be that when you create a template, each template would follow a format that encourages the proper use of terms.
Examples:
**Source description**:
    • Describes biological material
    • Allows only Characteristics
    • Has the format: **Source Name**, **Characteristics []**
**Study Protocol**:
    • Describes material acquisition
    • Allows Factors, Parameters, and Components
    • Has the format: **Protocol REF**, (Performer), (Date), **Factor []** and/or **Parameter []** and/or **Component []**, **Sample Name**
**Assay Protocol**:
    • Describes process of Material/Data extraction
    • Allows Factors, Parameters, and Components
    • Has the format: **Sample Name**, **Protocol REF**, (Performer), (Date), **Factor []** and/or **Parameter []** and/or **Component []**
**Assay Results**:
 Describes result of Material/Data extraction
    • Allows Characteristics
    • Has the format: **Extract Name**, **Characteristics []**

**Comment by StellaEggels** [comment]
Since this was addressed in nfdi4plants/Swate#316 and nfdi4plants/Swate#317, I believe this issue can be closed.
