### ISSUE TITLE
[TEMPLATE] Study information MPIMP Fernie

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/Swate-templates#64]
I want to add several templates related to metabolomics experiments as performed in our lab, starting here with a template for study information to fill isa.study.xlsx files. The templates are supposed to serve as a minimal set of information that should be annotated in future experiments and are therefore quite concise. I will reference this issue in the pull request.

**Comment by micwij** [comment]
I made pull requests for all templates that I currently want to add. I would leave this issue open until we successfully merged all of them.

**Comment by Brilator** [comment]
Hi, I've quickly checked your three lates templates

- #68, #70, #72 

> The templates are supposed to serve as a minimal set of information that should be annotated in future experiments and are therefore quite concise.

They're all fine, but just an idea: Since the templates are still mostly generic, I would suggest to (also) consider contributing to / add / improve the existing metabolomics templates. 
And maybe generate more specific templates for exactly the routines in your lab (e.g. for a specific combination of chromatography and MS or specific methods).

**Comment by Brilator** [comment]
Oh sorry, no. You're right, we don't want to mix those protocols. I just wanted to recommend adding (also) more specific protocols. I assume, external users come to your lab and ask for a specific type of measurement. With the templates you could ask them to provide exactly the metadata you need for that measurement. 

On a related note, please feel also free to contribute to the knowledge base via pull requests. 
I tried to write out a guide for platforms: 
https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/guides/ARC-enablingPlatforms.html

**Comment by micwij** [comment]
Ah, I see your point. Actually, currently I think most of our projects are internal. I like the guide for platforms. Creating a DataHUB group and an example ARC with pre-filled isa.json files could also be a good idea for us internally.

**Comment by micwij** [comment]
Quick question, before I close this issue. This and the other templates have been merged, but I do not yet see them on SWATE. Do I need to do anything else?

**Comment by Freymaurer** [comment]
Hey! Did you get emails with parsing fails? Maybe @Brilator can say more about this. If parsing errors were done, the templates will be available soon, but currently swate runs on an outdated engine.

**Comment by Freymaurer** [comment]
The [ARCitect ](https://github.com/nfdi4plants/ARCitect) can show all templates

**Comment by Brilator** [comment]
Hm, yes. From the swobup commit report (email) it looks like parsing errors. 
In case you don't receive it: 


> "Could not parse sheet "Metabolite Extraction": For the protocol with the name Extraction_protocol.txt, two different component lists Some([{ ComponentName = Some "methyl tert-butyl ether (CHEBI:27642)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methyl tert-butyl ether") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_27642" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "extraction buffer") TermSourceREF = Some "DPBO" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/DPBO_0000050" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }; { ComponentName = Some "methanol (CHEBI:17790)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methanol") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_17790" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "solvent") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_46787" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "5" }] } }]) and Some([{ ComponentName = Some "methanol (CHEBI:17790)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methanol") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_17790" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "extraction buffer") TermSourceREF = Some "DPBO" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/DPBO_0000050" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }; { ComponentName = Some "Chloroform (NCIT:C29815)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "Chloroform") TermSourceREF = Some "NCIT" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/NCIT_C29815" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "solvent") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_46787" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "5" }] } }]) were given, which is not allowed" @/api/IISADotNetCommonAPIv1/toSwateTemplateJson. |   | "Could not parse sheet "Metabolite Extraction": For the protocol with the name Extraction_protocol.txt, two different component lists Some([{ ComponentName = Some "methyl tert-butyl ether (CHEBI:27642)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methyl tert-butyl ether") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_27642" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "extraction buffer") TermSourceREF = Some "DPBO" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/DPBO_0000050" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }; { ComponentName = Some "methanol (CHEBI:17790)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methanol") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_17790" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "solvent") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_46787" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "5" }] } }]) and Some([{ ComponentName = Some "methanol (CHEBI:17790)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methanol") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_17790" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "extraction buffer") TermSourceREF = Some "DPBO" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/DPBO_0000050" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }; { ComponentName = Some "Chloroform (NCIT:C29815)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "Chloroform") TermSourceREF = Some "NCIT" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/NCIT_C29815" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "solvent") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_46787" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "5" }] } }]) were given, which is not allowed" @/api/IISADotNetCommonAPIv1/toSwateTemplateJson.
-- | -- | --
  | "Could not parse sheet "Metabolite Extraction": For the protocol with the name Extraction_protocol.txt, two different component lists Some([{ ComponentName = Some "methyl tert-butyl ether (CHEBI:27642)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methyl tert-butyl ether") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_27642" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "extraction buffer") TermSourceREF = Some "DPBO" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/DPBO_0000050" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }; { ComponentName = Some "methanol (CHEBI:17790)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methanol") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_17790" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "solvent") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_46787" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "5" }] } }]) and Some([{ ComponentName = Some "methanol (CHEBI:17790)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "methanol") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_17790" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "extraction buffer") TermSourceREF = Some "DPBO" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/DPBO_0000050" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }; { ComponentName = Some "Chloroform (NCIT:C29815)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "Chloroform") TermSourceREF = Some "NCIT" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/NCIT_C29815" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "solvent") TermSourceREF = Some "CHEBI" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/CHEBI_46787" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "5" }] } }]) were given, which is not allowed" @/api/IISADotNetCommonAPIv1/toSwateTemplateJson.

**Comment by Brilator** [comment]
The chromatography template should now become available. 

There was a classical Excel "pull-down" error leading to wrong ontology links ;) 

<img width="590" alt="Screenshot 2023-10-26 at 11 21 58" src="https://github.com/nfdi4plants/Swate-templates/assets/16229676/23968018-6cff-419a-974c-93400e2f3703">

**Comment by Brilator** [comment]
Apparently, differing values in `Component`s are also not allowed. 

> "Could not parse sheet "Mass spectrometry": For the protocol with the name mass_spec.txt, two different component lists Some([{ ComponentName = Some "Xcalibur (MS:1000532)" ComponentValue = Some (Ontology { ID = None Name = Some (Text "Xcalibur") TermSourceREF = Some "MS" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/MS_1000532" Comments = None }) ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "data processing software") TermSourceREF = Some "MS" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/MS_1001457" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }]) and Some([{ ComponentName = Some "genedata refiner" ComponentValue = Some (Name "genedata refiner") ComponentUnit = None ComponentType = Some { ID = None Name = Some (Text "data processing software") TermSourceREF = Some "MS" TermAccessionNumber = Some "http://purl.obolibrary.org/obo/MS_1001457" Comments = Some [{ ID = None Name = Some "ValueIndex" Value = Some "3" }] } }]) were given, which is not allowed" @/api/IISADotNetCommonAPIv1/toSwateTemplateJson.

That's fixed now in the mass spec template.

**Comment by Brilator** [comment]
Sorry, @micwij. I assigned those issues to myself a while ago and never took care of them. 

Your four templates are now all available within Swate. 
The issues was that component (just like protocol) building blocks cannot have different values. 
This is a bug that needs to be / or is already fixed with the new backend. 

So please have an eye on this, keep your example values (e.g. buffer components) in mind somewhere and add them again the future.

**Comment by micwij** [comment]
Okay great. Thanks for fixing it! I will have an eye on it and keep the example values elsewhere for the time being.
