### ISSUE TITLE
[BUG] Inconsistency between knowledgebase and Readme

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/Swate-templates#66]
There is a small difference between the contribution guide here in the README.md and in the Knowledgebase https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/guides/swate_template-contribution.html#creating-a-new-swate-template. Either forking first or creating the issue first. I would assume it is preferred to create the issue first in the original repository and fork afterwards, as described in the README.md. Otherwise you might create the issue in your own fork and then I am not sure if the original repository is notified of this. Correct me if I am wrong or maybe this is obvious for experienced Github users, but I just thought I would mention it.

**Comment by Brilator** [comment]
Good point, although I think by default the issue feature is disabled in forks. 
More importantly, I'll remove the instructions here and refer to the knowledge base so we don't have to maintain both.
