### ISSUE TITLE
[TEMPLATE] Metabolite extraction MPIMP Fernie

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/Swate-templates#67]
I want to add a concise template for metabolite extraction as performed in our lab as mentioned in #64. We mostly do an extraction with an extraction buffer that consists of MTBE:Methanol (3:1). For simplicity I only added one building block for the primary compound (MTBE). I was wondering though, if we have a general procedure for annotating solutions containing more than one compound, which I think are often used in different protocols.

**Comment by Brilator** [comment]
- Pragmatic: yes, just add it as one building block. 
- Less pragmatic, very informative, but a lot of work: you could describe creating your buffer as an ISA study / assay protocol. With inputs being e.g. the buffer salts, solvents, etc. (building blocks could be batch number, company, etc.) and output being the buffer, which you can then reference in another assay.
