### ISSUE TITLE
[FEATURE] Setup CI, testing Template conversion

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/Swate-templates#82]
We could add a GitHub action which runs on `PRs` to `main`. This action should test the conversion from the templates to json and fail if problems occur.

These errors might be: 
- Failing read in on xlsx
- Missing core descriptive fields in tempaltes
- Missing table in template
- Failing write to json

**Comment by Freymaurer** [comment]
auto update ARCtrl to newest before running script. This can be done with paket for example

**Comment by Freymaurer** [comment]
Maybe create issue directly from possible error reports

**Comment by Freymaurer** [comment]
Done!
