### ISSUE TITLE
Metadata Swate Template | Question | I can not import some of the database templates in SWATE

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/Swate-templates#84]
Hi, there is a new ticket via helpdesk.nfdi4plants.org, see below 
Recieved: 18.10.23

"Hi! When I try to import some of the database templates in SWATE (MIAPPE Metadata and MIAPPE Biological material), I get the following error message: 
`´An index satisfying the predicate was not found in the collection." @/api/IProtocolAPIv1/getProtocolById` and I can not even see the template. Any explanation? Thanks!"

**Comment by Hannah-Doerpholz** [comment]
Thank you for letting us know. We are aware that there is currently an issue with these templates and are working on it. We are currently updating our infrastructure for SWATE that will solve this issue. However, the updated version of SWATE is still being tested at the moment. Once the new version is available, the issue should be solved.

**Comment by Brilator** [comment]
Fixed for the particular template last week https://github.com/nfdi4plants/Swate-templates/pull/87
